language: rust

rust:
  - 1.0.0
  - beta
  - nightly

sudo: false

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

script:
  - cargo build --verbose
  - cargo test --verbose

# Using kcov for code coverage with coveralls.io.
# See hyper repo for a great example of using .travis.yml
# and for how to instruct TravisCI to compile and push docs
after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    mkdir kcov-master/build &&
    cd kcov-master/build &&
    cmake .. &&
    make &&
    make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/audio-* &&
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    [ $TRAVIS_RUST_VERSION = stable ] &&
    cargo doc --no-deps &&
    echo '<meta http-equiv=refresh content=0;url=audio/index.html>' > target/doc/index.html &&
    pip install ghp-import --user $USER &&
    $HOME/.local/bin/ghp-import -n target/doc &&
    git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

notifications:
  email: false